Config:
  SourceEnvName: "TEST"
  SourceServerName: "ContainerizedCluster"
  SourceServerType: "CLUSTER"
  TargetEnvName: "PROD"
  TargetServerName: "joker"
  TargetServerType: "SERVER"
  Applications:
    - ir-s-customer
#list of API Instance IDs that should be promoted
  Apis:
    - 9546857